sudo: required
language: python
python:
  - 3.5
env:
  - JUPYTERHUB=0.8 EXTRA_PIP='tornado<5'
  - JUPYTERHUB=0.9
services:
  - docker
before_install:
  - nvm install 10; nvm use 10
  - npm install -g configurable-http-proxy
  - pip install -v --pre -r dev-requirements.txt jupyterhub==${JUPYTERHUB}.* ${EXTRA_PIP}
install:
  - pip install -e .
script:
  - pyflakes dockerspawner tests
  - docker swarm init
  - docker pull jupyterhub/singleuser:$JUPYTERHUB
  - docker swarm init
  - travis_retry py.test --cov dockerspawner tests -v
